spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:batch
    username: ijunfu
    password: 123456
  h2:
    console:
      enabled: on
      path: /h2-console
  sql:
    init:
      schema-locations:
        - classpath:/org/springframework/batch/core/schema-drop-h2.sql
        - classpath:/org/springframework/batch/core/schema-h2.sql
      mode: always